import type { ProviderInfo, ModelCategory } from './types';

export const MODEL_CATEGORIES: { id: ModelCategory; name: string; icon: string }[] = [
  { id: 'chat', name: '对话模型', icon: '💬' },
  { id: 'image', name: '生图模型', icon: '🎨' },
  { id: 'video', name: '视频模型', icon: '🎬' },
  { id: 'audio', name: '语音模型', icon: '🎙️' },
];

export const DEFAULT_PROVIDERS: ProviderInfo[] = [
  // ============ 对话模型 ============
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'chat',
    baseUrl: 'https://chat.deepseek.com',
    apiPath: '/api/v1/chat/completions',
    models: [],
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'chat',
    baseUrl: 'https://claude.ai',
    apiPath: '/api/chat/completions',
    models: [],
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    category: 'chat',
    baseUrl: 'https://chat.openai.com',
    apiPath: '/api/chat/completions',
    models: [],
  },
  {
    id: 'gemini',
    name: 'Gemini',
    category: 'chat',
    baseUrl: 'https://generativelanguage.googleapis.com',
    apiPath: '/v1beta/models',
    models: [],
  },
  {
    id: 'qwen',
    name: 'Qwen',
    category: 'chat',
    baseUrl: 'https://chat.qwen.ai',
    apiPath: '/api/v1/chat/completions',
    models: [],
  },
  {
    id: 'kimi',
    name: 'Kimi',
    category: 'chat',
    baseUrl: 'https://kimi.moonshot.cn',
    apiPath: '/api/v1/chat/completions',
    models: [],
  },
  {
    id: 'doubao',
    name: '豆包',
    category: 'chat',
    baseUrl: 'https://www.doubao.com',
    apiPath: '/api/v1/chat/completions',
    models: [],
  },
  {
    id: 'grok',
    name: 'Grok',
    category: 'chat',
    baseUrl: 'https://api.grok.x.com',
    apiPath: '/v1/chat/completions',
    models: [],
  },
  {
    id: 'glm',
    name: '智谱 GLM',
    category: 'chat',
    baseUrl: 'https://chatglm.cn',
    apiPath: '/api/paa/v4/chat/completions',
    models: [],
  },
  {
    id: 'mistral',
    name: 'Mistral',
    category: 'chat',
    baseUrl: 'https://api.mistral.ai',
    apiPath: '/v1/chat/completions',
    models: [],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'chat',
    baseUrl: 'https://api.perplexity.ai',
    apiPath: '/chat/completions',
    models: [],
  },

  // ============ 生图模型 ============
  {
    id: 'midjourney',
    name: 'Midjourney',
    category: 'image',
    baseUrl: 'https://api.thenextleg.io',
    apiPath: '/v2/imagine',
    models: [],
  },
  {
    id: 'dalle',
    name: 'DALL-E',
    category: 'image',
    baseUrl: 'https://api.openai.com',
    apiPath: '/v1/images/generations',
    models: [],
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    category: 'image',
    baseUrl: 'https://api.stability.ai',
    apiPath: '/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image',
    models: [],
  },
  {
    id: 'flux',
    name: 'FLUX',
    category: 'image',
    baseUrl: 'https://api.runwayml.com',
    apiPath: '/v1/image/generation',
    models: [],
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    category: 'image',
    baseUrl: 'https://api.ideogram.ai',
    apiPath: '/v1/generations',
    models: [],
  },
  {
    id: 'recraft',
    name: 'Recraft',
    category: 'image',
    baseUrl: 'https://-api.recraft.ai',
    apiPath: '/v3/chat/completions',
    models: [],
  },

  // ============ 视频模型 ============
  {
    id: 'sora',
    name: 'Sora',
    category: 'video',
    baseUrl: 'https://api.openai.com',
    apiPath: '/v1/video/generations',
    models: [],
  },
  {
    id: 'runway',
    name: 'Runway',
    category: 'video',
    baseUrl: 'https://api.runwayml.com',
    apiPath: '/v1/videos/generations',
    models: [],
  },
  {
    id: 'pika',
    name: 'Pika',
    category: 'video',
    baseUrl: 'https://api.pika.art',
    apiPath: '/v1/videos/generations',
    models: [],
  },
  {
    id: 'kling',
    name: '快手可灵',
    category: 'video',
    baseUrl: 'https://api.klingai.com',
    apiPath: '/v1/videos/generations',
    models: [],
  },
  {
    id: 'hailuo',
    name: '海螺视频',
    category: 'video',
    baseUrl: 'https://api.hailuoai.com',
    apiPath: '/v1/video/generate',
    models: [],
  },
  {
    id: 'jianying',
    name: '剪映',
    category: 'video',
    baseUrl: 'https://lf-beijing-jym.bytedance.com',
    apiPath: '/api/jianying/v1/video/generate',
    models: [],
  },

  // ============ 语音模型 ============
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    category: 'audio',
    baseUrl: 'https://api.elevenlabs.io',
    apiPath: '/v1/text-to-speech',
    models: [],
  },
  {
    id: 'openai-audio',
    name: 'OpenAI Audio',
    category: 'audio',
    baseUrl: 'https://api.openai.com',
    apiPath: '/v1/audio/speech',
    models: [],
  },
  {
    id: 'cartesia',
    name: 'Cartesia',
    category: 'audio',
    baseUrl: 'https://api.cartesia.ai',
    apiPath: '/tts',
    models: [],
  },
  {
    id: 'lmnt',
    name: 'LMNT',
    category: 'audio',
    baseUrl: 'https://api.lmnt.com',
    apiPath: '/v1/synthesize',
    models: [],
  },
  {
    id: 'azure-tts',
    name: 'Azure TTS',
    category: 'audio',
    baseUrl: 'https://eastus.tts.speech.microsoft.com',
    apiPath: '/cognitiveservices/v1',
    models: [],
  },
  {
    id: 'minimax-audio',
    name: 'MiniMax 语音',
    category: 'audio',
    baseUrl: 'https://api.minimax.chat',
    apiPath: '/v1/t2a_v2',
    models: [],
  },
  {
    id: ' volcengine-tts',
    name: '火山引擎语音',
    category: 'audio',
    baseUrl: 'https://openspeech.bytedance.com',
    apiPath: '/api/v1/tts',
    models: [],
  },
  {
    id: 'iflytek',
    name: '讯飞语音',
    category: 'audio',
    baseUrl: 'https://tts-api.xfyun.cn',
    apiPath: '/v2/tts',
    models: [],
  },
];

export function getProvidersByCategory(category: ModelCategory): ProviderInfo[] {
  return DEFAULT_PROVIDERS.filter(p => p.category === category);
}

export function getProvider(id: string): ProviderInfo | undefined {
  return DEFAULT_PROVIDERS.find(p => p.id === id);
}
